# Generated by Django 2.2.4 on 2020-11-11 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0002_comment_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
