# Generated by Django 2.2.4 on 2020-11-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logapp', '0005_user_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
    ]
